# Generated by Django 2.1 on 2018-08-24 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklib', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='id',
        ),
        migrations.AlterField(
            model_name='book',
            name='book_name',
            field=models.CharField(max_length=48, primary_key=True, serialize=False),
        ),
    ]
