# Generated by Django 2.1 on 2018-08-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('salt', models.CharField(max_length=6)),
                ('pswmd5', models.CharField(max_length=32)),
            ],
        ),
    ]
